### PR TITLE
Added doAfterTerminate. Deprecated finallyDo.

### LINKED ISSUE #171: deprecate finallyDo( ) in favor of doAfterTerminate( )
See ReactiveX/RxJava#3566

### PR DESCRIPTION
**Pull request by phajduk**
Resolves #171 

@DavidMGross would it be possible to generate marbles for `doAfterTerminate`? I would like to add such marble to this documentation and to RxJava javadoc (at the moment there's is finallyDo.png file linked for `doAfterTerminate` operator). Is there any tool for generating marbles?

### CODE REVIEW

**Comment by DavidMGross** [comment]
The tool is called OmniGraffle Professional, and the source for the
diagrams can be found at
https://github.com/ReactiveX/RxJava/wiki/images/rx-operators/rx-operators.graffle

For historical reasons, this file is hosted at the RxJava wiki rather than
the ReactiveX website (
https://github.com/ReactiveX/RxJava/blob/1.x/CONTRIBUTING.md).  This may
change.  But for now, check it out/in from there.

On Thu, May 5, 2016 at 7:40 AM, Paweł Hajduk <notifications@github.com>
wrote:

> Resolves #171
> <https://github.com/ReactiveX/reactivex.github.io/issues/171>
>
> @DavidMGross <https://github.com/DavidMGross> would it be possible to
> generate marbles for doAfterTerminate? I would like to add such marble to
> this documentation and to RxJava javadoc (at the moment there's is
> finallyDo.png file linked for doAfterTerminate operator). Is there any
> tool for generating marbles?
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ReactiveX/reactivex.github.io/pull/239
> Commit Summary
>
>    - Added doAfterTerminate. Deprecated finallyDo.
>
> File Changes
>
>    - *M* documentation/operators.markdown
>    <https://github.com/ReactiveX/reactivex.github.io/pull/239/files#diff-0>
>    (1)
>    - *M* documentation/operators/do.html
>    <https://github.com/ReactiveX/reactivex.github.io/pull/239/files#diff-1>
>    (15)
>
> Patch Links:
>
>    - https://github.com/ReactiveX/reactivex.github.io/pull/239.patch
>    - https://github.com/ReactiveX/reactivex.github.io/pull/239.diff
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/reactivex.github.io/pull/239>
>



-- 
David M. Gross
PLP Consulting

**Comment by phajduk** [comment]
Unfortunately OmniGraffle is not available for my OS. I will create PNG file by hand but I won't be able to modify `rx-operators.graffle` file.

**Comment by phajduk** [comment]
@DavidMGross I rebased and squashed commits.

**Comment by DavidMGross** [comment]
Thanks! I'll make the associated change to the OmniGraffle file.

**Pull request merged**
