### PR TITLE
Fix wrong URL

### PR DESCRIPTION
**Pull request by gdrouet**
Current URLs lead to 404

### CODE REVIEW

**Comment by GeorgiKhomeriki** [comment]
This PR only affects the statically generated version of the site, as such the next time that the site is generated these changes will be gone. PRs should be changed and merged in the `develop` branch, after which the site can be re-generated and the static version can then be copied to the `master` branch, which is automatically deployed.

Long story short: this PR should be re-done in the `develop` branch.

**Comment by gdrouet** [comment]
ok :-)

**Comment by DavidMGross** [comment]
Georgi -

I screwed something up when trying to merge some of my develop work into
the master branch and I'm not savvy enough about git and/or Liquid to
understand where I failed and how to fix it.

I've finished drafts of the complete set of operator pages and they're
ready to merge when this is fixed.  Would you have some time to look into
this? Or could you give me some pointers to help me figure out where the
page building is failing on the site?

-- David

On Wed, Jan 7, 2015 at 9:14 AM, Guillaume DROUET <notifications@github.com>
wrote:

> ok :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/reactivex.github.io/pull/79#issuecomment-69055406>
> .
>



-- 
David M. Gross
PLP Consulting

**Comment by GeorgiKhomeriki** [comment]
Is the build failing locally when you run `rake`? If so, what is the error message? I can't check it out myself now because I'm on vacation and I don't have my computer with me.
If the build doesn't fail locally then you should simply copy the contents of the `_site` directory (this contains the generated static site) to the master branch and commit/push that. So you shouldn't directly try to merge `develop` into `master`.

Hope this helps. If not, I'll try to get to some machine where I can build the site tonight.

**Comment by DavidMGross** [comment]
My local rake build works fine. But since I tried to merge I get the
message "The tag `lang_operator` in `documentation/operators/all.html` is
not a recognized Liquid tag. For more information, see
https://help.github.com/articles/page-build-failed-unknown-tag-error."

Is the plan to only have the generated static site in the master branch?  I
didn't pick up on that.


On Wed, Jan 7, 2015 at 11:40 PM, Georgi Khomeriki <notifications@github.com>
wrote:

> Is the build failing locally when you run rake? If so, what is the error
> message? I can't check it out myself now because I'm on vacation and I
> don't have my computer with me.
> If the build doesn't fail locally then you should simply copy the contents
> of the _site directory (this contains the generated static site) to the
> master branch and commit/push that. So you shouldn't directly try to merge
> develop into master.
>
> Hope this helps. If not, I'll try to get to some machine where I can build
> the site tonight.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/reactivex.github.io/pull/79#issuecomment-69145909>
> .
>



-- 
David M. Gross
PLP Consulting

**Comment by GeorgiKhomeriki** [comment]
Yes, that's indeed the plan. We switched to this workflow because GitHub doesn't allow for custom Jekyll plugins (like the lang_operator). This was mentioned in this (rather long) [discussion](https://github.com/ReactiveX/reactivex.github.io/issues/20). So the idea is to never merge any branch into `master`. The `develop` branch is where all development takes place, and where PRs should be directed. The site should be built locally and the resulting static version committed to the `master` branch to deploy it.

**Comment by DavidMGross** [comment]
Ah. Yes. That does sound familiar. I think I must have lost a brain cell or
two over the holidays.

On Thu, Jan 8, 2015 at 9:23 AM, Georgi Khomeriki <notifications@github.com>
wrote:

> Yes, that's indeed the plan. We switched to this workflow because GitHub
> doesn't allow for custom Jekyll plugins (like the lang_operator). This was
> mentioned in this (rather long) discussion
> <https://github.com/ReactiveX/reactivex.github.io/issues/20>. So the idea
> is to never merge any branch into master. The develop branch is where all
> development takes place, and where PRs should be directed. The site should
> be built locally and the resulting static version committed to the master
> branch to deploy it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/reactivex.github.io/pull/79#issuecomment-69214449>
> .
>



-- 
David M. Gross
PLP Consulting

**Pull request merged**
