### PR TITLE
Add RxSwift Community Information

### PR DESCRIPTION
**Pull request by freak4pc**

### CODE REVIEW

**Comment by freak4pc** [comment]
Thanks for merging this @DavidMGross . Do you know by any chance how often the website is deployed? Seems like the content isn't reflected yet.

**Comment by DavidMGross** [comment]
Traditionally it's happened periodically but irregularly, when I get around to it. But the client who had been subsidizing my work on the Rx docs is no longer doing so, so this sort of work has fallen to the bottom of my priority list. I think we need someone else to step up and volunteer to keep the docs site updated.

**Comment by freak4pc** [comment]
Keeping the doc site updated is one thing, but keeping it aligned with GitHub would be easier for the time being. 

On the RxSwift Community repo we have a script that deploys it after every merge to `develop` and also dail (via CI). Would you be interesting in pursuing something like that?

**Comment by DavidMGross** [comment]
I remember we looked into that at some point years ago and there was some hurdle in the way at the time (I don't remember what), but I can't see in principle why we couldn't make that work. I don't have time to commit to it myself, though.

**Comment by freak4pc** [comment]
I wouldn't mind but I think I would need much more information that I don't have at the moment (like where the site is currently hosted, authentication to it, etc.) which might make it not worthwhile to let an external contributor do this? 

Regardless, if it's not too much trouble to pass that knowledge on, I don't mind making some CI/CD pipeline for this.

**Pull request merged**
