### PR TITLE
Adds Airbnb logo to frontpage

### PR DESCRIPTION
**Pull request by felipecsl**
How it looks like:
screen shot 2015-12-03 at 5 46 03 pm

### CODE REVIEW

**Comment by felipecsl** [comment]
sorry, I had to check internally first. All clear now, reopening.

**Comment by spikebrehm** [comment]
It would be nice to use a PNG instead of JPG, but no biggie.

**Comment by felipecsl** [comment]
yeah I got this from the [press page](https://www.airbnb.com/press/resources) which only had the jpg version, but i'd be happy to replace if you can point me to a png version

**Comment by felipecsl** [comment]
Anyone looking at this?

**Comment by staltz** [comment]
Looks good to merge IMO

**Pull request merged**
