### PR TITLE
Update RxScala scaladoc to 0.23.1

### PR DESCRIPTION
**Pull request by zsxwing**

### CODE REVIEW

**Comment by zsxwing** [comment]
cc @GeorgiKhomeriki

**Comment by samuelgruetter** [comment]
Suggestion: It would be nice to have the RxScala version in the title of the html page (this is achieved by setting `val version` in `build.sbt`).

**Comment by GeorgiKhomeriki** [comment]
I've pushed these changes to the `develop` branch as well. Next time please do a PR on the `develop` branch, since that contains the actual source code for the website. The `master` branch contains a generated static version, it also serves as the "production" branch. Changes that are not in `develop` will be gone next time the site is built and deployed.

**Comment by zsxwing** [comment]
@GeorgiKhomeriki OK. Thank you.

**Comment by zsxwing** [comment]
> Suggestion: It would be nice to have the RxScala version in the title of the html page (this is achieved by setting val version in build.sbt).

@samuelgruetter I need to use `scalacOptions in (Compile, doc) ++= (Opts.doc.title("RxScala") ++ Opts.doc.version("0.23.1"))` in build.sbt to set the title. However, there is a problem for this one. The title will always be RxScala 0.23.1 no matter which class I click. Do you know how to change the tittle according to the class name?

**Comment by samuelgruetter** [comment]
Hm that's interesting... The scaladoc of the old rxscala.github.io page (https://github.com/RxScala/RxScala.github.io/tree/original/scaladoc) displayed the version automatically in the html title, but somehow this went lost. I don't know if it's because of an update in scaladoc, or because we switched from gradle to sbt.

**Pull request merged**
